import { Process, Processor } from '@nestjs/bull';
import { InjectRedis } from '@nestjs-modules/ioredis';
import { AppLoggerService } from '../../../common/logger/app-logger.service';
import { Job } from 'bull';
import { Redis } from 'ioredis';
import { UsageRepository } from '../usage.repository';
import { CostCalculatorService } from '../cost-calculator.service';
import {
  BudgetCheckerService,
  secondsUntilEndOfMonth,
} from '../budget-checker.service';

export interface UsageJobData {
  requestId: string;
  tenantId: string;
  apiKeyId: string;
  provider: string;
  model: string;
  requestedModel: string;
  status: 'success' | 'error' | 'cached' | 'rate_limited';
  cacheHit: boolean;
  cacheType?: 'exact' | 'semantic';
  promptTokens: number;
  completionTokens: number;
  costUsd: number;
  latencyMs: number;
  ttfbMs?: number;
  stream: boolean;
  errorCode?: string;
  createdAt: string; // ISO timestamp
  /** Always set — UUID generated by GatewayService if caller omits x-session-id. */
  sessionId: string;
  /** Optional tenant-supplied label from x-user-id header. */
  userLabel?: string;
}

@Processor('usage')
export class UsageJob {
  private readonly logger = new AppLoggerService(UsageJob.name);

  constructor(
    private readonly usageRepo: UsageRepository,
    private readonly costCalculator: CostCalculatorService,
    private readonly budgetChecker: BudgetCheckerService,
    @InjectRedis() private readonly redis: Redis,
  ) {}

  @Process('track-usage')
  async process(job: Job<UsageJobData>): Promise<void> {
    // Shallow copy so we can patch costUsd without mutating the job data
    const data: UsageJobData = { ...job.data };

    // Step 1: Calculate cost if not already set.
    // GatewayService pre-calculates cost on the non-streaming path, but
    // streaming sends costUsd=0 (no token counts until stream ends).
    // The job recalculates here as the safety net for both cases.
    if (data.costUsd === 0 && data.status === 'success') {
      data.costUsd = await this.costCalculator.calculateCost(
        data.provider,
        data.model,
        data.promptTokens,
        data.completionTokens,
      );
    }

    // Step 2: Write request record
    await this.usageRepo.createRequest(data);

    // Step 3: Create RequestSpan for session tracing.
    // FK on requestId — must run after createRequest so the parent row exists.
    await this.usageRepo.createRequestSpan({
      sessionId: data.sessionId,
      tenantId: data.tenantId,
      requestId: data.requestId,
      userLabel: data.userLabel,
    });

    // Step 4: Upsert daily aggregates
    await this.usageRepo.upsertDailyUsage(data);

    // Step 5: Record latency sample in Redis sorted set for DailyCloseJob p95 computation.
    // ZADD tenant:{id}:latency:{provider}:{model}:{YYYY-MM-DD} score=latencyMs member=requestId
    // Key TTL: 48 hours — DailyCloseJob deletes the key after processing.
    if (data.latencyMs !== undefined) {
      const date = new Date(data.createdAt).toISOString().split('T')[0];
      const latencyKey = `tenant:${data.tenantId}:latency:${data.provider}:${data.model}:${date}`;
      await this.redis.zadd(latencyKey, data.latencyMs, data.requestId);
      await this.redis.expire(latencyKey, 48 * 60 * 60);
    }

    // Step 6: Log completion
    this.logger.log('Usage tracked', {
      requestId: data.requestId,
      tenantId: data.tenantId,
      provider: data.provider,
      model: data.model,
      tokens: data.promptTokens + data.completionTokens,
      costUsd: data.costUsd,
      latencyMs: data.latencyMs,
    });

    // Step 7: Budget check — BudgetCheckerService logs warn/error internally.
    // Fire after DB writes so the sum in usage_daily already includes this request.
    const budget = await this.budgetChecker.checkBudget(
      data.tenantId,
      data.costUsd,
    );

    if (budget.status === 'exceeded') {
      // Set a Redis flag that RateLimitGuard checks on every request.
      // TTL = seconds until end of current month so the block auto-lifts
      // at the start of the new billing period.
      await this.redis.set(
        `tenant:${data.tenantId}:budget:exceeded`,
        '1',
        'EX',
        secondsUntilEndOfMonth(),
      );
    }
  }
}
